#test

name: Deploy to AWS EC2

on:
    push:
        branches:
        - test

env: 
    AWS_DB_URL: ${{ secrets.AWS_DB_URL }}
    AWS_DB_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
    AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
    AWS_DB_NAME: ${{ secrets.AWS_DB_NAME }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSHë¡œ EC2ì— ì ‘ì†í•˜ê¸°
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script_stop: true
          script: |
            cd /home/ubuntu/BE-Starbucks-Renewal
            git pull origin test
            chmod +x ./gradlew  # ì‹¤í–‰ ê¶Œí•œ ì¶”ê°€

            echo "ðŸ” AWS_DB_URL: ${AWS_DB_URL}"
            echo "ðŸ” AWS_DB_USERNAME: ${AWS_DB_USERNAME}"
            echo "âœ… í™˜ê²½ë³€ìˆ˜ í™•ì¸ ì™„ë£Œ"

            
            echo "spring.datasource.url=${AWS_DB_URL}" > src/main/resources/application-dev.yml
            echo "spring.datasource.username=${AWS_DB_USERNAME}" >> src/main/resources/application-dev.yml
            echo "spring.datasource.password=${AWS_DB_PASSWORD}" >> src/main/resources/application-dev.yml

            
            ./gradlew clean build -x test
            fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
